version: "3.7"
services:
  db:
    build: mysql
    image: venture_db
    container_name: venture_db
    ports:
      - 13306:3306
  app:
    build: rails
    links:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: venture_app
    container_name: venture_app
    ports:
      - 3000:3000
    volumes:
      - ./rails:/venture
    depends_on:
      - db